### ISSUE TITLE
Tagging Quotes

### ISSUE THREAD

**Issue by Zulleyy3** [MegaMasterX/ColonelBot-v3#1]
So we can have them in our hands. Like Boktai let us do with the sun.

**Comment by MegaMasterX** [comment]
At this time, Quote Tagging would add extra steps to users trying to simply add quotes to the bot. It would require an extra layer of moderation and more data to keep tabs on. At this time, a quote tagging feature is not planned.  When v3 is launched, you are more than welcome to fork the repo and implement it yourself. 

Sorry :(
