### ISSUE TITLE
Make !delete default to a certain size.

### ISSUE THREAD

**Issue by Zulleyy3** [MegaMasterX/ColonelBot-v3#3]
usage of the !delete command showed that we prefer to delete all the newest commands+colbot responses, defaulting to "!delete 100" all the time.

Make !delete (without additional parameter) default to that, please.

**Comment by MegaMasterX** [comment]
!delete is planned to default to a message size of 5 (Should be enough to cover at least 2 commands worth of chat messages.)  

This feature will be wrapped into ModeratorModule.cs rather than its own individual Module file, as it falls under moderation.

Base for !delete is in commit 2a786521.

**Comment by MegaMasterX** [comment]
!delete completed in 07c211f
